### ISSUE TITLE
SlackApiUsersProfileGetRequest user field is not Option<SlackUserId>

### ISSUE THREAD

**Issue by dmcrosby** [abdolence/slack-morphism-rust#100]
Per the Slack API docs (https://api.slack.com/methods/users.profile.get)

The user field is nullable, this would allow a bot author to retrieve the current user/bot's information. Which may be useful in seeing what messages it has sent before.

**Comment by abdolence** [comment]
Thanks for reporting this. Yes, this seems inconsistent, I'll prepare the fix.

**Comment by abdolence** [comment]
Fixed and will be released in couple of days in v0.31.0
