### ISSUE TITLE
Add Reactions API

### ISSUE THREAD

**Issue by jtmichelson** [abdolence/slack-morphism-rust#153]
Add the following methods:
* [reactions_add](https://api.slack.com/methods/reactions.add)
* ~~[reactions_get](https://api.slack.com/methods/reactions.get)~~ added in #139 
* [reactions_list](https://api.slack.com/methods/reactions.list)
* [reactions_remove](https://api.slack.com/methods/reactions.remove)

Implementation should be similar to the chat methods in [chat.rs](https://github.com/abdolence/slack-morphism-rust/blob/df4d69af0ae75b2953d9e56e9232855459285d6d/src/api/chat.rs). Most, if not all, of the models already exist (e.g. `SlackApiReactionAddRequest` would be composed of `SlackChannelId`, `SlackReaction`, and `SlackTs`).

**Comment by jtmichelson** [comment]
I cannot currently assign myself to this issue or push a new branch to create a pull request. Does someone need to grant me permissions?

**Comment by abdolence** [comment]
Hey, @jtmichelson 
It seems you want to propose some PR and the changes which is great ❤️ 
In order you do that you just need to follow common GitHub flow:
- Fork a repository
- Create a feature branch
- Create a PR from your fork to this repository with the changes

Let me know if you need help with this.

**Comment by abdolence** [comment]
Awesome updates, release in v1.3.3 🎉
