### ISSUE TITLE
`SlackEventsApiMiddlewareService` loses all information from the original request

### ISSUE THREAD

**Issue by abusch** [abdolence/slack-morphism-rust#155]
Hi,

I've started using this crate in a project and for the most part if works great! The only issue I've noticed is in the Axum middleware: it looks like after decoding/verifying the incoming request, it creates a new empty `Request` and only bothers setting the decoded body in it. In doing so, all other information about the original request is lost i.e. `request_uri`, extensions, headers... It would be great to preserve this information (in particular any extension).

**Comment by abdolence** [comment]
Hey, thanks for reporting this! I think I've improved this and fixed it in the latest master. Will release shortly in the new version.

**Comment by abdolence** [comment]
Released in https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.3.4

Let me know if this doesn't work for you.

**Comment by abusch** [comment]
Just tested the new release and it works fine now. Thanks for the prompt fix!
