### ISSUE TITLE
De-serializing views requires optional parameters to be present

### ISSUE THREAD

**Issue by x3ro** [abdolence/slack-morphism-rust#164]
Hey! Thanks for building this library, it's made playing around with the Slack API from Rust a lot easier 🚀

What I've been trying to do is open a modal from my app. I tried to create a view in the [Block kit builder](https://app.slack.com/block-kit-builder), and then deserialize it into the model that you provide in your application, like so:

```rust
const VIEW_JSON: &str = include_str!("modal.json");
let view: SlackModalView = serde_json::from_str(viewstr).unwrap();
```

The modal JSON generated by the block kit builder is the following:

```json
{
	"title": {
		"type": "plain_text",
		"text": "Add info to feedback",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Save",
		"emoji": true
	},
	"type": "modal",
	"blocks": [
		{
			"type": "input",
			"element": {
				"type": "plain_text_input"
			},
			"label": {
				"type": "plain_text",
				"text": "Label",
				"emoji": true
			}
		}
	]
}
```

Now, I would expect this to de-serialize without error, but instead it seems to require the fields marked as `#[serde(with = "serde_with::rust::string_empty_as_none")]` to be present. If I understand the Slack API docs correctly, these should be optional fields.  An example error is

```
Error("missing field `callback_id`", line: 17, column: 1)
```

There's a good chance I'm just holding it wrong™, since this is the first time I'm working with the Slack API. I'd be happy to contribute an example once I figure out how this work 😅

**Comment by abdolence** [comment]
Hey, oh dear. This is a bug, but I never bumped into this since Slack in the real life returns empty string in those fields all the time (and they're probably not doing that in the builder).

I believe this should help:
https://github.com/abdolence/slack-morphism-rust/pull/165

**Comment by abdolence** [comment]
Can you test your code with the latest master now (before I release it soon) please?

**Comment by x3ro** [comment]
Ah nice! I'll try it out and get back to you, thanks :)

**Comment by x3ro** [comment]
Using the latest master branch does indeed fix the de-serialization issue! I'll be using that for now 🚀

**Comment by abdolence** [comment]
Thanks for the report and tests!

**Comment by abdolence** [comment]
Released in https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.4.2
