### ISSUE TITLE
How to use SlackClientHttpConnector for SlackClient?

### ISSUE THREAD

**Issue by ox4ka5h** [abdolence/slack-morphism-rust#167]
### Discussed in https://github.com/abdolence/slack-morphism-rust/discussions/166

<div type='discussions-op-text'>

<sup>Originally posted by **ox4ka5h** January 26, 2023</sup>
   
    let client = SlackClient::new(<SlackClientHttpConnector>);
    let token_value: SlackApiTokenValue = "xoxb---".into();
    let token: SlackApiToken = SlackApiToken::new(token_value);
    let session = client.open_session(&token);

    let post_chat_req =
     SlackApiChatPostMessageRequest::new("#reports".into(),
            SlackMessageContent::new().with_text("Hey there! pinged from rust".into())
    );

    let post_chat_resp = session.chat_post_message(&post_chat_req).await?;

</div>

**Comment by abdolence** [comment]
Answered in the Q&A. Let's close this issue (we can open it if we have something to implement more from that). I read discussions as well as issues - so thanks for submitting it as a discussion!
