### ISSUE TITLE
Missing `state` field for block actions payload

### ISSUE THREAD

**Issue by fabianlindfors** [abdolence/slack-morphism-rust#172]
Hi again! I'm working with block actions and it seems like the `state` field is missing from `SlackInteractionBlockActionsEvent`. It's documented here: https://api.slack.com/reference/interaction-payloads/block-actions#fields

Thanks! :)

**Comment by abdolence** [comment]
Hey, keep them coming if you find more :)

This should work now after this PR
https://github.com/abdolence/slack-morphism-rust/pull/173

Available on the master branch, let me know if it doesn't work for you.

**Comment by abdolence** [comment]
Released in v1.6.1
