### ISSUE TITLE
How can I update my activity? ? 

### ISSUE THREAD

**Issue by SirMishaa** [abdolence/slack-morphism-rust#174]
Hello, 

Thank you for your wrapper. 
I'd like to add some automation to my activity (The status message and the indicator if I'm online or offline) 

Do I need to keep open a client to be considered as online? Or can I use only the API/SDK?
And how can I set my activity and the presence indicator using the SDK? I can't find it in the documentation

Kind regards!

**Comment by abdolence** [comment]
Hey, this is the official doc:
https://api.slack.com/docs/presence-and-status

> There's no way to force a user status to active.
You can only control bots presense (somehow, the page above describes it).

**Comment by SirMishaa** [comment]
Okay, thanks for the link and for the answer

**Comment by abdolence** [comment]
Yes, it exists in the library:
https://github.com/abdolence/slack-morphism-rust/blob/f1dc1ab8142b03f4b10eb0b840717c8a6c250941/src/api/users.rs#L151
