### ISSUE TITLE
Missing rustfmt.toml?

### ISSUE THREAD

**Issue by mtsr** [abdolence/slack-morphism-rust#18]
Hi Abdulla,

Thanks for your work on this project!

I was working on a fork of the project to see if I can make it independent of tokio (and maybe hyper) and noticed that the pre-push hook fails for me on an unchanged project. Could you check if you have a custom format config that is missing from git?

**Comment by abdolence** [comment]
Hey Jonas,

I don't have any special configs no, maybe you have some kind of global configs or something? I would notice because I work on different machines from time to time.
What is the output?

**Comment by abdolence** [comment]
Another guess is maybe we have different versions of rust tools and they were updated recently, let me check it.

**Comment by mtsr** [comment]
Thanks for the quick response.

It's a few lines in a generic type. I'll copy it later. I did check whether I had any rustfmt.toml, but I'll recheck.

**Comment by abdolence** [comment]
cargo clippy --version:
> clippy 0.0.212 (e1884a8 2020-12-29)

cargo fmt --version:
> rustfmt 1.4.25-stable (0f29ff6 2020-11-11)

**Comment by mtsr** [comment]
Ah. I was still defaulted to nightly. My bad.

Maybe you could change the hook to `cargo +stable fmt --all -- --check`.

**Comment by abdolence** [comment]
Not sure if this possible with
https://github.com/rhysd/cargo-husky
, because I'm using it for this
If you find an easy way - I'd gladly change it :)

**Comment by abdolence** [comment]
Out of curiosity, why you need this without Tokio?

**Comment by mtsr** [comment]
I was looking at using `tide`, which uses `async-std`, which can theoretically support `tokio` based libraries, but it would be even easier without it.

But seeing the amount of change in this particular part of the ecosystem, maybe this can wait and I can just focus on the problem I actually want to solve, haha.

**Comment by abdolence** [comment]
hm, interesting. I'll think about extracting abstraction layer inside to provide the ability to support different libraries natively.

**Comment by abdolence** [comment]
Meanwhile, closing this as we know now the origin of the issue.

**Comment by abdolence** [comment]
@mtsr 
> I was looking at using `tide`, which uses `async-std`, which can theoretically support `tokio` based libraries, but it would be even easier without it.

In case you still looking for this, I've just implemented more modular design with v0.5 that extracts all Hyper/Tokio specific code in a separate module.
All contributions are welcome 👍🏻 indeed.
