### ISSUE TITLE
Missing event types: `block_suggestion` UrlEncoded payload POST from slack and a the required response for populating a dropdown

### ISSUE THREAD

**Issue by noxasaxon** [abdolence/slack-morphism-rust#186]
I'm working on getting a PR through, but before i forget i wanted to drop a note here for future users.

- [Slack Docs for a Select Menu with an external data source](https://api.slack.com/reference/block-kit/block-elements#external_select)
- [Slack docs for responding to this POST with a list of up to 100 options](https://api.slack.com/reference/block-kit/block-elements#external_select__setup)
- [outdated documentation on what this payload used to look like](https://api.slack.com/legacy/interactive-message-field-guide#options_load_url)
- [what this payload can look like now, hidden away in the Socket Mode docs.](https://api.slack.com/apis/connections/socket-implement#menu)
    - I only found this by using a google search limited to the slack api website with "block_suggestion" query, and its the only time in the docs that this is mentioned

<img width="920" alt="image" src="https://user-images.githubusercontent.com/34722463/236599705-5a503cfd-d0ce-434e-8d06-5de657940ca9.png">

and heres a scrubbed example of what the URL post is from slack (when used in a View Modal). note the type is `block_suggestion` and its sent as a url encoded params (Form extractor in Axum):

```json
{
    "payload": {
        "type": "block_suggestion",
        "user": {
            "id": "<user_id>",
            "username": "<name>",
            "name": "<name>",
            "team_id": "<team_id>"
        },
        "container": {
            "type": "view",
            "view_id": "<view_id>"
        },
        "api_app_id": "<api_app_id>",
        "token": "<token>",
        "action_id": "<action_id>",
        "block_id": "<block_id>",
        "value": "test",
        "team": {
            "id": "<team_id>",
            "domain": "<domain>",
            "enterprise_id": "<enterprise_id>",
            "enterprise_name": "<enterprise_name>"
        },
        "enterprise": {
            "id": "<ent_id>",
            "name": "ent_name>"
        },
        "is_enterprise_install": false,
        "view": {
            ...<view_obj>
        }
    }
}
```

**Comment by noxasaxon** [comment]
SlackInteractionEvent will need a new variant, BlockSuggestion

```rust
pub enum SlackInteractionEvent {
    #[serde(rename = "block_actions")]
    BlockActions(SlackInteractionBlockActionsEvent),
    #[serde(rename = "dialog_submission")]
    DialogSubmission(SlackInteractionDialogueSubmissionEvent),
    #[serde(rename = "message_action")]
    MessageAction(SlackInteractionMessageActionEvent),
    #[serde(rename = "shortcut")]
    Shortcut(SlackInteractionShortcutEvent),
    #[serde(rename = "view_submission")]
    ViewSubmission(SlackInteractionViewSubmissionEvent),
    #[serde(rename = "view_closed")]
    ViewClosed(SlackInteractionViewClosedEvent),
}
```

**Comment by abdolence** [comment]
Hey, great you're working on it 🏆 
Thanks for detail info and the links!

Let me know if you need any help from me.

**Comment by nnishimura** [comment]
I noticed this issue has been stale for a while - I also needed to add this to my project's fork. I'd love to take this over 👍

**Comment by abdolence** [comment]
@nnishimura thanks for adding this quickly.
This is released now in https://github.com/abdolence/slack-morphism-rust/releases/tag/v2.5.0
