### ISSUE TITLE
Error on reaction_added events

### ISSUE THREAD

**Issue by CircuitSacul** [abdolence/slack-morphism-rust#201]
```rs
json_error: Error("unknown variant `reaction_added`, expected one of `message`, `app_home_opened`, `app_mention`, `app_uninstalled`, `link_shared`, `emoji_changed`, `member_joined_channel`, `member_left_channel`, `channel_created`, `channel_deleted`, `channel_archive`, `channel_rename`, `channel_unarchive`, `team_join`, `file_created`, `file_change`, `file_deleted`, `file_shared`, `file_unshared`, `file_public`", line: 0, column: 0),
```

There's probably other events that aren't handled, but this is just one I came across.

**Comment by abdolence** [comment]
Hey,

Yes, the event types support is incomplete, so I added it when I bump into something missing or someone else opens a PR for that. Not ideal, but unfortunately the documentation from Slack is sometimes misleading or obsolete, so all of them need to be verified.

This should help:
https://github.com/abdolence/slack-morphism-rust/pull/202

Can you help with the testing using the feature branch connecting to the real Slack server, so I can merge it?

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by abdolence** [comment]
Released in https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.14.0
Thanks for the report!
