### ISSUE TITLE
`SlackAppMentionEvent` doesn't include `edited` field

### ISSUE THREAD

**Issue by phyber** [abdolence/slack-morphism-rust#207]
Hi,

The `SlackAppMentionEvent` struct doesn't include the `edited` field, so it's not currently possible to detect if an `AppMention` is being triggered due to a user editing their message to the bot.

While not explicitly called out in the [`app_mention`](https://api.slack.com/events/app_mention) documentation, the field does exist on an edited bot mention, just like it does in the [`message`](https://api.slack.com/events/message) event and the `app_mention` documentation indicates it exists with the following comment:

> `app_mention` events are just like other `message` events sent over the Events API, but their type indicates `app_mention`.

I had a look through the other fields on the `SlackAppMentionEvent` struct just in case the `edited` field was tucked away somewhere else, but it doesn't appear to be.

Would it be possible to have the `edited` field added to the event?

Thanks.

**Comment by abdolence** [comment]
Hey,

Thanks for the report.
It should work now in
https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.14.2
