### ISSUE TITLE
Re-export `http::status::StatusCode`

### ISSUE THREAD

**Issue by willbush** [abdolence/slack-morphism-rust#223]
Thanks for the work on slack-morphism-rust! Recently, when dependabot was updating dependencies on my slack bot, it tried to update http from 0.2 to 1.0 which breaks the compilation.

Which made me wonder if `http::status::StatusCode` could be re-exported so I don't have to take a direct dependency on `http`?

I [noticed](https://github.com/abdolence/slack-morphism-rust/pull/219) you already have a bot submitting PR updates for dependencies, and I was just wondering how it compares to dependabot?

**Comment by abdolence** [comment]
Hey, it makes sense for http crate, I agree. I'll update this.

I think Renovate bot is a bit more flexible and provides those controls such as rebase and nicer PRs, it also supported more build tools formats for different languages than dependabot when I choose to work with it.
Overall I don't think it is much better, more like I used to this one.

**Comment by willbush** [comment]
> Released in https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.16.0

Thanks! I just wanted to confirm I was able to switch to using the re-exported type and remove `http` from my `Cargo.toml`.
