### ISSUE TITLE
Socket mode in a tokio task breaks on Ctrl-C.

### ISSUE THREAD

**Issue by Gremious** [abdolence/slack-morphism-rust#231]
Putting `socket_mode_listener.serve().await;` into a `tokio::spawn(async move { ... })`, then hitting `Ctrl-C` makes tokio panic with

```
thread 'ctrl-c' panicked at C:\Users\Gremious\.cargo\registry\src\index.crates.io-6f17d22bba15001f\slack-morphism-1.16.1\src\hyper_tokio\socket_mode\tokio_clients_manager.rs:169:48:
Could not send signal on channel.: SendError { .. }
```

This is on Windows with PowerShell.

Letting the socket sit in actual `main` and hitting `Ctrl-C` there works just fine, thankfully.

**Comment by abdolence** [comment]
Hey,
if you want to use your own lifecycle instead of `serve` using tokio::spawn, there is normal API with start() and stop().

`serve` is just a wrapping method created for convenience/examples.

**Comment by Gremious** [comment]
Oh I just wanted to run it in main, and hit `Ctrl-C` to exit, nothing fancy. So just using `serve` for convenience.

Thing is, I also run a [client/listener for a discord bot](https://docs.rs/serenity/0.12.0/serenity/client/struct.Client.html#method.start) in the same app, so at least one of those 2 `.await`s nees to go into their own tokio task. 

Sending a `Ctrl-C` while discord serenity's client is inisde a task is handled gracefuly, thankfully, so I do that - but Morphism - not so much.

**Comment by abdolence** [comment]
Yeah, as I suspected you have other stuff to run and await :)
You need to use
1. `slack.start().await` <- this will be returned as soon as it is ready 
2. `discord_client.start().await` // Not sure if they're blocking thread or not
3. your own handler for signals (you can use ctrlc yourself if you want)
4. `slack.shutdown().await` <- to disconnect from Slack server for Socket Mode
5. other cleanups (discord?)

**Comment by abdolence** [comment]
The nature of an error is coming from the ctrlc implementation:
https://detegr.github.io/doc/ctrlc/fn.set_handler.html#

> Should only be called once, typically at the start of your program

I suspect someone else already set it.

**Comment by Gremious** [comment]
Ahh, thank you, your example actually makes the api a lot clearer. I (wasn't awake enough and) didn't read hard enough into it, so I had assumed I would've needed to setup events to send signals or some such, but it's just two split calls - appreciate it!

My qualms have been resolved, I'll let you handle closing the issue in the hopes that

**Comment by abdolence** [comment]
Well, if it works for you, then I'll close this issue, since as I mentioned, `serve` is just using ctrlc for Windows (if you look at the source code, it just 3-4 lines of code).
In real life application start/shutdown is a way to go.
