### ISSUE TITLE
Proposal: Organising type names and re-exports for v2

### ISSUE THREAD

**Issue by siketyan** [abdolence/slack-morphism-rust#236]
In this crate, may symbols are re-exported everywhere. This may causes namespace pollution. For example, the root module re-exports 152 structs and 6 enums. This is not common in Rust crates. I think symbols should be imported from the separated namespaces. How do you think about this? Before releasing v2, should we remove unnecessary re-exports and minimise the duplicated importing paths?

**Comment by abdolence** [comment]
Hey, most of the structures exported (if not all of them) intentionally prefixed with `Slack` so I don't expect this is a pollution problem for anyone really.  However I'm open to suggestion if you see better structure, what do you have on your mind, can you show me a small example to imports?

**Comment by siketyan** [comment]
@abdolence Agree that namespace pollution is not likely to occur with Slack prefix. However, some types have very long name. I suggest that removing unnecessary prefixes and prefer using proper module paths instead. For instance, `SlackApiChatPostMessageRequest` will be `api::chat::PostMessageRequest`. This helps the users to use shorter name in the context that is specific to Slack APIs. I'll submit a PR as a proposal later!

**Comment by abdolence** [comment]
We need to think about the migration cost here, since I would like to avoid the changes that require a lot of modifications from people using the crate. Please bear in mind this as well, so we won't have the problem that I need to support long term v1 and V2 :)

**Comment by abdolence** [comment]
Now since 2.0 is released, probably this is not something we're going to do in the foreseeable future.
Thanks for the suggestion, we may return to this for v3 :)

https://github.com/abdolence/slack-morphism-rust/releases/tag/v2.0.0
