### ISSUE TITLE
Allow dynamic Slack API base URL

### ISSUE THREAD

**Issue by dax** [abdolence/slack-morphism-rust#246]
For testing purposes (ie. testing with a mock server), I would like to be able to inject a dynamically computed Slack API base URL.

Instead of using the hardcoded `SLACK_API_URI_STR` base URL, while building a `SlackClientHttpConnector`, I would like to inject the mock URL instead so that I can control what is returned to the Slack client.

What would be the best way to do it?

**Comment by abdolence** [comment]
I think this PR should help:
https://github.com/abdolence/slack-morphism-rust/pull/247

**Comment by abdolence** [comment]
Now connectors can override URLs.

An example for Hyper:
```
SlackClient::new(SlackClientHyperConnector::new()?.with_slack_api_url("https://example.net"))
```

**Comment by dax** [comment]
Wow, that was fast.
I tested it and it works like a charm. Thank you very much 🙏
