### ISSUE TITLE
`SlackHeaderBlock` should only take `SlackBlockPlainText`

### ISSUE THREAD

**Issue by gagbo** [abdolence/slack-morphism-rust#272]
When I had this block

```
slack_blocks![
        some_into(SlackHeaderBlock::new(md!("{}", command.get_name()))),
]
```

sent in a [chat.postEphemeral API call](https://api.slack.com/methods/chat.postEphemeral), I received an `invalid_blocks` error even if the compilation passed. Turns out that the header block doc explicitely says that the [`text` element should be a `plain_text` element](https://api.slack.com/reference/block-kit/blocks#header_fields). Making this change made the call work

```diff
slack_blocks![
-        some_into(SlackHeaderBlock::new(md!("{}", command.get_name()))),
+        some_into(SlackHeaderBlock::new(pt!("{}", command.get_name()))),
]
```

I didn’t check if it’s possible to change the header block to only accept plain text, but if it’s possible it would be nice

**Comment by abdolence** [comment]
Yes, there is a way to restrict it:
https://github.com/abdolence/slack-morphism-rust/pull/273
