### ISSUE TITLE
Usage of the multipart API

### ISSUE THREAD

**Issue by frankruegamer** [abdolence/slack-morphism-rust#275]
Since Slack is deprecating the [`files.upload`](https://api.slack.com/methods/files.upload) endpoint (and it already stopped working for me), I'm trying to make use of the newer [`files.getUploadURLExternal`](https://api.slack.com/methods/files.getUploadURLExternal) API.  
This is already greatly simplified with slack-morphism, however the usage of multipart endpoints in the form of `session.http_post_multipart_form` or rather `connector.http_post_uri_multipart_form` requires the `FileMultipartData` struct which doesn't seem to be exported from the crate.  

Though ideally the crate would support the new file upload API out of the box, having access to `FileMultipartData` should be all that's necessary for now to build the `files.getUploadURLExternal` workflow ourselves.

**Comment by abdolence** [comment]
Hey, thanks for reporting!

I've been playing around this in this PR:
https://github.com/abdolence/slack-morphism-rust/pull/276

Seems Slack doesn't actually support multipart/form uploads via new API using upload URLs. They expect either raw file upload or `multipart form encoded`. 

> status_code: 500, http_response_body: Some("internal error: put")

I'll need some time to add that, but nothing stops me to add one more method to upload binary via POST, just need time.

**Comment by abdolence** [comment]
This should work now in https://github.com/abdolence/slack-morphism-rust/releases/tag/v2.3.0

**Comment by frankruegamer** [comment]
Thank you for the quick reply and a fix, it's working beautifully.
