### ISSUE TITLE
Problems for use getUploadURLExternal and completeUploadExternal

### ISSUE THREAD

**Issue by GRANCASMII** [abdolence/slack-morphism-rust#280]
Hi guys, I have been tried use this new features after of be deprecated the last method, but i has been impossible, do you have the form for use these methods? the documentation is incomplet, thaanks

**Comment by abdolence** [comment]
What kind of problems?
Have you seen this example?

https://github.com/abdolence/slack-morphism-rust/blob/1ab447825e14b9de4862b58927572d60cf3bd1a0/examples/client.rs#L85
