### ISSUE TITLE
More unknown event subtypes

### ISSUE THREAD

**Issue by statiolake** [abdolence/slack-morphism-rust#294]
In #283, I reported that there's an unsupported subtype: `huddle_thread`. Now I found two more unknown subtypes: `share_shortcut` and `canvas_updated`.

Should we add something like `SlackMessageEventType::Unknown(String)`? It seems no complete list of subtypes...

**Comment by abdolence** [comment]
Hey, we kind of collecting them using the reports like this. It is not ideal, but at least we accumulating those all types. Maybe if this keep happening all the time we will endup with `unknown` approach, but I don't think we're there yet and it is a small work to update the list.
I'll release the patch soon.

**Comment by abdolence** [comment]
Thanks for the report, keep them coming :)

https://github.com/abdolence/slack-morphism-rust/releases/tag/v2.6.1

**Comment by statiolake** [comment]
Thank you for the quick response again! I understand your position and appreciate it. I'll let you know if I find any other issues.
