### ISSUE TITLE
Fix wrong subtype: `canvas_updated` -> `channel_canvas_updated`

### ISSUE THREAD

**Issue by statiolake** [abdolence/slack-morphism-rust#299]
I'm sorry but my previous report in #294 is actually wrong: it should be `channel_canvas_updated` instead of `canvas_updated`.

**Comment by abdolence** [comment]
No worries, I've fixed it in #302

**Comment by abdolence** [comment]
https://github.com/abdolence/slack-morphism-rust/releases/tag/v2.7.0
