### ISSUE TITLE
Error when using example

### ISSUE THREAD

**Issue by dlpnet** [abdolence/slack-morphism-rust#3]
Just running the example get me this error:
[2020-09-01][18:44:28][test][INFO] Loading server: 127.0.0.1:8080
Error: NotPresent

Any idea ?
Thanks

**Comment by abdolence** [comment]
The example bot requires to work the following environment variables (with values from your Slack bot profile in api.slack.com):
- SLACK_CLIENT_ID, SLACK_CLIENT_SECRET, SLACK_BOT_SCOPE, SLACK_REDIRECT_HOST - for OAuth
- SLACK_SIGNING_SECRET for all routes

I updated a bit docs and diagnostics in the example related to this.

**Comment by dlpnet** [comment]
Thank you, the diagnostics are a lot better. How is SLACK_BOT_SCOPE supposed to be formatted with all the scopes ?

**Comment by abdolence** [comment]
Try commas without spaces. Let me know if it doesn't help.

**Comment by abdolence** [comment]
Also might be useful:

Routes for this example are available on http://<your-host>:8080:

- /auth/install - to begin OAuth installation
- /auth/callback - a callback endpoint for Slack OAuth profile config
- /push - for Slack Push Events
- /interaction - for Slack Interaction Events
- /command - for Slack Command Events

**Comment by dlpnet** [comment]
Thank you ! Actually I didn't see that, . I am only using the interaction events for now. Where do you put your own code to process the event?

**Comment by abdolence** [comment]
If you need only interaction events, your example is more simple:

```rust
async fn slack_server_example(
    client: Arc<SlackClient>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8080));
    info!("Loading server: {}", addr);

   async fn test_interaction_events_function(event: SlackInteractionEvent, _client: Arc<SlackClient>) {
    println!("{:#?}", event);
   }

    async fn your_others_routes(
        _req: Request<Body>,
    ) -> Result<Response<Body>, Box<dyn std::error::Error + Send + Sync>> {
        Response::builder()
            .body("Hey, this is a default users route handler".into())
            .map_err(|e| e.into())
    }

    let interactions_events_config = Arc::new(SlackInteractionEventsListenerConfig::new(
        config_env_var("SLACK_SIGNING_SECRET")?,
    ));

    let make_svc = make_service_fn(move |_| {
        let thread_interaction_events_config = interactions_events_config.clone();
        let listener =
            SlackClientEventsListener::new(client.clone()).with_error_handler(test_error_handler);
        async move {
            let routes = chain_service_routes_fn(
                listener.interaction_events_service_fn(
                    thread_interaction_events_config,
                    test_interaction_events_function,
                ),
                your_others_routes,
            );


            Ok::<_, Box<dyn std::error::Error + Send + Sync>>(service_fn(routes))
        }
    });

    let server = hyper::server::Server::bind(&addr).serve(make_svc);
    server.await.map_err(|e| {
        error!("Server error: {}", e);
        e.into()
    })
}
```

For this example above, your own code should be put in: `test_interaction_events_function`.

**Comment by dlpnet** [comment]
So it looks like I am using the push events then ... I configured Slack to send events to the push handler. That's working.
You should probably have an example of sending (postMessage) in your example after you receive a push but I figured out how to do it.
And for your documentation: SLACK_TEST_TOKEN should also be set.

For now all good ! thank you

**Comment by abdolence** [comment]
Right now, the current example mostly about showing how to use API. It wasn't supposed to be used as a template for bots. This is why environment variables and others are more decision that you should make in your own solution - maybe you need to configure it somehow more appropriate.

You can look also at the Web API client docs: https://slack-rust.abdolence.dev/web-api.html related to the client.

> Any chance to discuss with you directly? I still have some questions and using git for that is maybe not optimal.
If you have some questions that involve your particular solution and you don't want to disclose some details you can ping me using Twitter DM for example. Also, I'm quite sure that we have different timezones :)

But if you have general questions, I'd suggest continuing here to help others. Probably your questions might help others as well.

**Comment by dlpnet** [comment]
Let's continue here then. I am using this project to learn rust so my questions are probably basic rust instead of morphism related. I appreciate the help. 
How do you access the data from `event: SlackPushEvent`? Let's say for example to access the event.channel value

**Comment by abdolence** [comment]
No worries.
I'm writing this on my smartphone, so sorry if I made a dump mistype.

PushEvent is an enum, so first you need to use match:

```rust
match event {
  case SlackPushEvent.EventCallback(callback) => {
      match callback.event {
        case SlackEventCallbackBody.SlackMessageEvent(message) => { 
           // Now you have here message with channel and body, etc
         println("{}", message.origin.channel)
     }
  }
}

```

The thing that we have enums here that Slack Events API provides different kind of events, and they implemented in Rust as enums.

**Comment by dlpnet** [comment]
I saw that but I got fooled by the match in push_events.rs ! Thank you.
Just for others with the correction:
`match event {
        SlackPushEvent::EventCallback(callback) => {
            match callback.event {
              SlackEventCallbackBody::Message(message) => { 
                // Now you have here message with channel and body, etc
                println!("{}", message.origin.ts)
                },
                _ => { }
            }
        },
        _ => { }
    }`

**Comment by abdolence** [comment]
> but I got fooled by the match in push_events.rs

That's internal code helping to verify URLs for you, so you don't have to do it yourself.

**Comment by dlpnet** [comment]
I moved a little bit further. I needed to check https://github.com/abdolence/rust-value-struct and https://github.com/abdolence/rust-struct-builder also to see how to work with the req and send messages. 

Is it the correct way to get the data back:
let userID = message.sender.user.unwrap().value();

and for comparison should I use the userID above 
`if userID == "XXX"`

or a 
```
match message.sender.user
 { Some(id) => ...} 
```

?

**Comment by abdolence** [comment]
First of as I predicted before I obviously sent you a Rust/Scala mix of code because I was on a smartphone and now I've updated it to the proper one. That happens when you code a lot in different languages simultaneously, so sorry if was confusing.

Regarding to your questions related to userId, this is what I'd do in that case:

```rust
                    message.sender.user
                        .filter(|user_id| user_id == SlackUserId("some-your-value".into()) )
                        .map ( |user_id| {
                            // Whatever you want to deail with user_id here
                           unimplemented!()
                        });
```

I suppose my own code style inclines more to FP, so I'm not sure if that fits for everyone.

Now, about `SlackClientSession`. Treat it like a lightweight object that stores a reference to your token and gives you access to all of the available Slack Web API methods that require that token.

So, in case if you deal only one token you can keep it almost globally for all your threads and requests.

(This is where Rust actually shines. Because it isn't a mutable one the library can't even detect if it the same session or not, so it can't change its state at all).

**Comment by dlpnet** [comment]
Thanks for the detailed explanation ! It helps a lot.
