### ISSUE TITLE
Support socket mode

### ISSUE THREAD

**Issue by LegNeato** [abdolence/slack-morphism-rust#48]
It would be great to support https://api.slack.com/apis/connections/socket. Do you see any issues creating something like `slack-morphism-socket` and doing everything over a websocket rather than via http/hyper? Are there any http assumptions in this lib?

**Comment by abdolence** [comment]
Ok, the PR now is ready to use I think. I'm testing it and polishing mostly.

**Comment by abdolence** [comment]
Implemented in 0.10.0.
The example: https://github.com/abdolence/slack-morphism-rust/blob/master/src/hyper/examples/socket_mode.rs
