### ISSUE TITLE
Error handler for socket mode callbacks

### ISSUE THREAD

**Issue by fussybeaver** [abdolence/slack-morphism-rust#54]
Not sure if it's entirely related to socket mode, but I'm finding that errors bubbled up in the callback functions get swallowed without a log message (unless I handle it inline):

```
async fn slack_command_events_fn(
    event: SlackCommandEvent,
    client: Arc<SlackHyperClient>,
    states: Arc<RwLock<SlackClientEventsUserStateStorage>>,
) -> Result<SlackCommandEventResponse, Box<dyn std::error::Error + Send + Sync>> {
            match something_that_might_fail {
                Ok(_) => (),
                Err(e) => {
                    error!("Failed: {:#?}", e);
                    return Err(e.into());
                }
            };
}
```

I thought maybe the `error_handler` defined on the [`SlackClientEventsListenerEnvironment`](https://docs.rs/slack-morphism/0.12.0/slack_morphism/listener/struct.SlackClientEventsListenerEnvironment.html#method.with_error_handler) would trigger, but looking through the code that's more for the initial socket connection?

**Comment by abdolence** [comment]
Your expectation are correct, let me look into this. 
Again, thanks for testing the new mode. I don't have the opportunity myself doing the same right now (I use Event API more), so keep them coming if you see any other inconsistences.

**Comment by abdolence** [comment]
Ah, now I realised you were talking about particularly errors from user defined callbacks/functions. The thing is the currently we have only one function that able to return some result and error - this is for slash command/ events function. Let me have a look if I we have that as well.

**Comment by abdolence** [comment]
I'll try to improve the error handling for the next version for all of the callback functions.

**Comment by fussybeaver** [comment]
Yeah, it's more ergonomics... Thanks for planning it for the next release.

**Comment by abdolence** [comment]
Improved in v0.14.0. Unfortunately, it affects user API, but I think it is worth it in the long run.
https://github.com/abdolence/slack-morphism-rust/releases/tag/v0.14.0

**Comment by abdolence** [comment]
Don't ask me what happened with v0.13.0 🙈

**Comment by fussybeaver** [comment]
Thanks, just been working with it - works fine!
