### ISSUE TITLE
What is the recommended way to share a slack session?

### ISSUE THREAD

**Issue by noxasaxon** [abdolence/slack-morphism-rust#69]
I am building a slack bot using Slack Morphism with the `Axum` web framework and because I am only using one token, I'd like to share the client session around. 

Currently I have not found a way to share the session in an arc because the "client" is dropped while borrowed, so I have been creating a struct to hold the Client & Token together, and creating the session in each parent thread as needed. 

Also with the recent Slack Morphism changes, I've now needed to include `hyper` & `hyper-rustls` in my cargo.toml just to be able to specify the new type of a slack client and slack session. Is there a way around this?

demo repo demonstrating these issues: https://github.com/noxasaxon/slack-axum-demo

Thanks!

**Comment by abdolence** [comment]
Hey, this is an interesting case. Let's discuss if we can find better ergonomics for this.
`SlackClientSession` is just a lightweight object that was just supposed to be used for consequent calls using the same token in one function and I don't share it personally.

My code is usually read some token (from database/file/environment) for a particular identified workspace, and creates those sessions all the time just to have multiple consequent calls to Web APIs in one rust function without specifying token parameter all the time. This was the main purpose for it.

Why not just to share your token between threads + `Arc<SlackClient>` everywhere you need? Let me check your source code.

**Comment by abdolence** [comment]
> Also with the recent Slack Morphism changes, I've now needed to include hyper & hyper-rustls in my cargo.toml just to be able to specify the new type of a slack client and slack session. Is there a way around this?

Let me check this as well.

**Comment by abdolence** [comment]
> Also with the recent Slack Morphism changes, I've now needed to include hyper & hyper-rustls in my cargo.toml just to be able to specify the new type of a slack client and slack session. Is there a way around this?

Ok, this was required in your example just because you didn't use type alias:
![image](https://user-images.githubusercontent.com/1316837/142936710-aed85d0a-8c7e-4ee7-ba74-4066c401963d.png)

**Comment by abdolence** [comment]
There is also type alias:
`SlackHyperClient = SlackClient<SlackClientHyperHttpsConnector>` which you may find useful.

**Comment by abdolence** [comment]
I see that you were trying to share this, and if you use only one token per-app this is something you need more. You don't need to worry about session objects, it is just a reference to token + client to call multiple methods from Web API in one Rust function, so you can easily create them millions if needed - they are cheap.

```
    // let slack_workaround = Arc::new(SlackStateWorkaround {
    //     bot_token: slack_bot_token,
    //     slack_client,
    // });
```

**Comment by abdolence** [comment]
Another thing I noticed in your demo, that you didn't protect your routes - for the production you may want to use `SlackEventSignatureVerifier` (as it is used for hyper routes out of the box).

**Comment by noxasaxon** [comment]
thanks for the quick responses! 

I've updated the code to use the Type Aliases you specified, and this let me remove the `hyper` dependencies 🙇 

Good point about the fact that there are unauthenticated slack API calls, I'll continue sharing around a struct with the Client and Bot Token so that I can make those calls as needed. 


> Another thing I noticed in your demo, that you didn't protect your routes - for the production you may want to use SlackEventSignatureVerifier (as it is used for hyper routes out of the box).

Good catch! Yeah my plan is to hook up the signature verifier before it goes live, but i want to try and include it as an Axum middleware for the Slack specific routes and haven't had time to dive down that rabbit hole yet 😆.

thanks a ton for your help and for making this library!

**Comment by noxasaxon** [comment]
Closing this issue, but first I wanted to leave code for people to find later if they want to use Axum/Tower with slack-morphism. I updated the [demo repo](https://github.com/noxasaxon/slack-axum-demo/blob/main/src/verification.rs) with a an Axum/Tower middleware service, and you can choose to [add it as a service layer ](https://github.com/noxasaxon/slack-axum-demo/blob/main/src/main.rs#L39-L51), where it will protect only the routes above it. Then you can add more (non-slack) routes below it.

Thanks again for your help!

**Comment by noxasaxon** [comment]
Hey @abdolence, my bot made it to open source if you're curious how it all turned out. Thanks so much for your help again!

https://github.com/twilio-labs/receptionist-bot-rs

**Comment by abdolence** [comment]
@noxasaxon Cool stuff, thanks for sharing this. Stories like this give additional motivations :)

PS Feel free to submit PRs if you see absent functions like Reactions API :P

**Comment by noxasaxon** [comment]
Haha yeah I forgot to follow up on that one, will do 👍
